name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write   # for die Workload Identity

    steps:
      # Check out the repository
      - name: Check out the repository
        uses: actions/checkout@v3

      # Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/70756149774/locations/global/workloadIdentityPools/github-actions/providers/github-repos'
          service_account: 'hshn-devsecops-service-account@hs-heilbronn-devsecops.iam.gserviceaccount.com'

      # Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: 'hs-heilbronn-devsecops'  

      # Deploy to Google Cloud Run
      - name: Deploy to Google Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: note-api-hs-heilbronn-devsecops-schartaj  
          image: gcr.io/hs-heilbronn-devsecops/note-api:${{ github.sha }}
          region: europe-west3  
          project_id: 'hs-heilbronn-devsecops'
          env_vars: BACKEND=memory
